export const products = [
  // Clothing Products
  {
    id: 1,
    name: "Relaxed Short full Sleeve T‑Shirt",
    category: "Clothes",
    price: 45,
    oldPrice: 60,
    rating: 3,
    img: "/img/products/clothes-1.jpg",
  },
  {
    id: 2,
    name: "Girls pink Embro design Top",
    category: "Clothes",
    price: 61,
    oldPrice: 80,
    rating: 4,
    img: "/img/products/clothes-2.jpg",
  },
  {
    id: 3,
    name: "Black Floral Wrap Midi Skirt",
    category: "Clothes",
    price: 76,
    oldPrice: 90,
    rating: 5,
    img: "/img/products/clothes-3.jpg",
  },
  {
    id: 4,
    name: "Classic Blue Denim Jacket",
    category: "Clothes",
    price: 85,
    oldPrice: 110,
    rating: 4,
    img: "/img/products/clothes-4.jpg",
  },
  // Shirts
  {
    id: 5,
    name: "Pure Garment Dyed Cotton Shirt",
    category: "Mens Fashion",
    price: 68,
    oldPrice: 85,
    rating: 4,
    img: "/img/products/shirt-1.jpg",
  },
  {
    id: 6,
    name: "Slim Fit Casual Shirt",
    category: "Mens Fashion",
    price: 72,
    oldPrice: 90,
    rating: 5,
    img: "/img/products/shirt-2.jpg",
  },
  // Jackets
  {
    id: 7,
    name: "Winter Puffer Jacket",
    category: "Jackets",
    price: 120,
    oldPrice: 150,
    rating: 5,
    img: "/img/products/jacket-1.jpg",
  },
  {
    id: 8,
    name: "Hooded Bomber Jacket",
    category: "Jackets",
    price: 110,
    oldPrice: 140,
    rating: 4,
    img: "/img/products/jacket-2.jpg",
  },
  {
    id: 9,
    name: "Classic Leather Jacket",
    category: "Jackets",
    price: 200,
    oldPrice: 250,
    rating: 5,
    img: "/img/products/jacket-3.jpg",
  },
  {
    id: 10,
    name: "Denim Trucker Jacket",
    category: "Jackets",
    price: 95,
    oldPrice: 120,
    rating: 4,
    img: "/img/products/jacket-4.jpg",
  },
  {
    id: 11,
    name: "Windbreaker Jacket",
    category: "Jackets",
    price: 80,
    oldPrice: 100,
    rating: 3,
    img: "/img/products/jacket-5.jpg",
  },
  {
    id: 12,
    name: "Quilted Down Jacket",
    category: "Jackets",
    price: 130,
    oldPrice: 160,
    rating: 5,
    img: "/img/products/jacket-6.jpg",
  },
  // Shoes
  {
    id: 13,
    name: "Classic White Sneakers",
    category: "Shoes",
    price: 60,
    oldPrice: 80,
    rating: 4,
    img: "/img/products/shoe-1.jpg",
  },
  {
    id: 14,
    name: "White Sneakers (Alt View)",
    category: "Shoes",
    price: 60,
    oldPrice: 80,
    rating: 4,
    img: "/img/products/shoe-1_1.jpg",
  },
  {
    id: 15,
    name: "Black Running Shoes",
    category: "Shoes",
    price: 75,
    oldPrice: 95,
    rating: 5,
    img: "/img/products/shoe-2.jpg",
  },
  {
    id: 16,
    name: "Black Running Shoes (Alt View)",
    category: "Shoes",
    price: 75,
    oldPrice: 95,
    rating: 5,
    img: "/img/products/shoe-2_1.jpg",
  },
  {
    id: 17,
    name: "Brown Leather Loafers",
    category: "Shoes",
    price: 90,
    oldPrice: 120,
    rating: 4,
    img: "/img/products/shoe-3.jpg",
  },
  {
    id: 18,
    name: "Red Sports Sneakers",
    category: "Shoes",
    price: 65,
    oldPrice: 85,
    rating: 3,
    img: "/img/products/shoe-4.jpg",
  },
  {
    id: 19,
    name: "Blue Canvas Shoes",
    category: "Shoes",
    price: 55,
    oldPrice: 70,
    rating: 4,
    img: "/img/products/shoe-5.jpg",
  },
  // Jewelry & Accessories
  {
    id: 20,
    name: "Elegant Gold Necklace",
    category: "Jewelry & Accessories",
    price: 150,
    oldPrice: 200,
    rating: 5,
    img: "/img/products/jewellery-1.jpg",
  },
  {
    id: 21,
    name: "Silver Hoop Earrings",
    category: "Jewelry & Accessories",
    price: 40,
    oldPrice: 55,
    rating: 4,
    img: "/img/products/jewellery-2.jpg",
  },
  {
    id: 22,
    name: "Diamond Stud Earrings",
    category: "Jewelry & Accessories",
    price: 220,
    oldPrice: 300,
    rating: 5,
    img: "/img/products/jewellery-3.jpg",
  },
  {
    id: 23,
    name: "Classic Leather Watch",
    category: "Jewelry & Accessories",
    price: 95,
    oldPrice: 130,
    rating: 4,
    img: "/img/products/watch-1.jpg",
  },
  {
    id: 24,
    name: "Brown Leather Belt",
    category: "Jewelry & Accessories",
    price: 35,
    oldPrice: 50,
    rating: 3,
    img: "/img/products/belt.jpg",
  },
  // Sports & Activewear
  {
    id: 25,
    name: "Men's Sports T‑Shirt",
    category: "Sports & Activewear",
    price: 30,
    oldPrice: 40,
    rating: 4,
    img: "/img/products/sports-1.jpg",
  },
  {
    id: 26,
    name: "Women's Yoga Pants",
    category: "Sports & Activewear",
    price: 45,
    oldPrice: 60,
    rating: 5,
    img: "/img/products/sports-2.jpg",
  },
  {
    id: 27,
    name: "Running Shorts",
    category: "Sports & Activewear",
    price: 25,
    oldPrice: 35,
    rating: 3,
    img: "/img/products/sports-3.jpg",
  },
  {
    id: 28,
    name: "Sports Bra",
    category: "Sports & Activewear",
    price: 28,
    oldPrice: 38,
    rating: 4,
    img: "/img/products/sports-4.jpg",
  },
  {
    id: 29,
    name: "Men's Track Jacket",
    category: "Sports & Activewear",
    price: 55,
    oldPrice: 70,
    rating: 4,
    img: "/img/products/sports-5.jpg",
  },
  {
    id: 30,
    name: "Women's Sports Jacket",
    category: "Sports & Activewear",
    price: 60,
    oldPrice: 80,
    rating: 5,
    img: "/img/products/sports-6.jpg",
  },
  // Shorts
  {
    id: 31,
    name: "Denim Shorts",
    category: "Shorts",
    price: 35,
    oldPrice: 45,
    rating: 4,
    img: "/img/products/shorts-1.jpg",
  },
  {
    id: 32,
    name: "Cotton Cargo Shorts",
    category: "Shorts",
    price: 38,
    oldPrice: 50,
    rating: 3,
    img: "/img/products/shorts-2.jpg",
  },
  // Party Wear
  {
    id: 33,
    name: "Sequin Party Dress",
    category: "Party Wear",
    price: 120,
    oldPrice: 160,
    rating: 5,
    img: "/img/products/party-wear-1.jpg",
  },
  {
    id: 34,
    name: "Velvet Blazer",
    category: "Party Wear",
    price: 140,
    oldPrice: 180,
    rating: 4,
    img: "/img/products/party-wear-2.jpg",
  },
  // Personal Care
  {
    id: 35,
    name: "Luxury Perfume",
    category: "Personal Care",
    price: 70,
    oldPrice: 90,
    rating: 5,
    img: "/img/products/perfume.jpg",
  },
  {
    id: 36,
    name: "Herbal Shampoo",
    category: "Personal Care",
    price: 25,
    oldPrice: 35,
    rating: 4,
    img: "/img/products/shampoo.jpg",
  },
  // Numbered Images (Generic)
  {
    id: 37,
    name: "Basic White Tee",
    category: "Clothes",
    price: 20,
    oldPrice: 30,
    rating: 3,
    img: "/img/products/1.jpg",
  },
  {
    id: 38,
    name: "Classic Blue Jeans",
    category: "Clothes",
    price: 50,
    oldPrice: 65,
    rating: 4,
    img: "/img/products/2.jpg",
  },
  {
    id: 39,
    name: "Summer Dress",
    category: "Clothes",
    price: 55,
    oldPrice: 70,
    rating: 4,
    img: "/img/products/3.jpg",
  },
  {
    id: 40,
    name: "Men's Polo Shirt",
    category: "Mens Fashion",
    price: 40,
    oldPrice: 55,
    rating: 3,
    img: "/img/products/4.jpg",
  },
];
